# Generated by Django 5.1.3 on 2024-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('new_york', 'New York'), ('los_angeles', 'Los Angeles'), ('chicago', 'Chicago'), ('houston', 'Houston'), ('phoenix', 'Phoenix'), ('philadelphia', 'Philadelphia'), ('san_antonio', 'San Antonio'), ('san_diego', 'San Diego')], max_length=50),
        ),
    ]
