# Generated by Django 5.1.3 on 2024-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke'), ('iskele', 'İskele'), ('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt')], max_length=50),
        ),
    ]
