# Generated by Django 5.1.3 on 2024-11-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke'), ('iskele', 'İskele'), ('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
