# Generated by Django 5.1.3 on 2024-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_location_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Girne', 'Girne'), ('Lefkoşa', 'Lefkoşa'), ('Lefke', 'Lefke'), ('İskel', 'İskele'), ('Gazimağusa', 'Gazimağusa'), ('Güzelyurt', 'Güzelyurt')], max_length=50, null=True),
        ),
    ]
