# Generated by Django 5.1.3 on 2024-12-15 22:00

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1 555 123 4567', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
