# Generated by Django 5.1.3 on 2024-12-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_disasteralert_user_alter_disasteralert_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='location',
            field=models.CharField(choices=[('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke'), ('iskele', 'İskele'), ('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='disasteralert',
            name='user',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
