# Generated by Django 5.1.3 on 2024-12-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_disasteralert_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='type',
            field=models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Wild Fire', 'Wild Fire'), ('Tsunami', 'Tsunami')], max_length=50),
        ),
    ]
