# Generated by Django 5.1.3 on 2024-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_disasteralert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteralert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alert_images/'),
        ),
        migrations.AlterField(
            model_name='disasteralert',
            name='severity',
            field=models.CharField(choices=[('High', 'High'), ('Mediem_High', 'Mediem_High'), ('Mediem', 'Mediem'), ('Mediem_Low', 'Mediem_Low'), ('Low', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='disasteralert',
            name='type',
            field=models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Wild Fire', 'Wild Fire'), ('Tsunami', 'Tsunami'), ('Hurricane', 'Hurricane'), ('Tornado', 'Tornado'), ('Landslide', 'Landslide'), ('Drought', 'Drought'), ('Volcanic Eruption', 'Volcanic Eruption'), ('Snowstorm', 'Snowstorm'), ('Avalanche', 'Avalanche'), ('Heatwave', 'Heatwave'), ('Cyclone', 'Cyclone'), ('Blizzard', 'Blizzard'), ('Sandstorm', 'Sandstorm')], max_length=50),
        ),
    ]
