# Generated by Django 5.1.3 on 2024-12-14 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_disasteralert_image_alter_disasteralert_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
