# Generated by Django 5.1.3 on 2024-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alter_disasteralert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
