# Generated by Django 5.1.3 on 2024-12-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_disasteralert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='location',
            field=models.CharField(choices=[('Girne', 'Girne'), ('Lefkoşa', 'Lefkoşa'), ('Lefke', 'Lefke'), ('İskel', 'İskele'), ('Gazimağusa', 'Gazimağusa'), ('Güzelyurt', 'Güzelyurt')], max_length=50),
        ),
    ]
