# Generated by Django 5.1.3 on 2024-12-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alter_disasteralert_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasteralert',
            name='severity',
            field=models.CharField(choices=[('High', 'High'), ('Mediem High', 'Mediem High'), ('Mediem', 'Mediem'), ('Mediem Low', 'Mediem Low'), ('Low', 'Low')], max_length=50),
        ),
    ]
